name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA::7})"

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/k8s-express-test:${{ steps.short-sha.outputs.sha }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: kcearns/k8s-express-helm
          event-type: update-values
          client-payload: '{"tag": "${{ steps.short-sha.outputs.sha }}"}'